{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "prj": {
      "defaultValue": "at-arm",
      "type": "string"
    },
    "env": {
      "defaultValue": "test",
      "type": "string"
    },
    "servername": {
      "defaultValue": "winsvr",
      "type": "string"
    },
    "username": {
      "defaultValue": "azureuser",
      "type": "string"
    },
    "password": {
      "type": "securestring"
    }
  },
  "variables": {
    "virtualMachines_name": "[concat(parameters('prj'),'-',parameters('env'),'-',parameters('servername'),'-vm')]",
    "virtualMachines_username": "[parameters('username')]",
    "virtualMachines_password": "[parameters('password')]",
    "virtualMachines_osdisk": "[concat(parameters('prj'),'-',parameters('env'),'-',parameters('servername'),'-os-disk')]",
    "virtualNetworks_name": "[concat(parameters('prj'),'-',parameters('env'),'-vnet')]",
    "networkSecurityGroups_name": "[concat(parameters('prj'),'-',parameters('env'),'-vnet-main-nsg')]",
    "publicIPAddresses_name": "[concat(parameters('prj'),'-',parameters('env'),'-',parameters('servername'),'-ip')]",
    "networkInterfaces_name": "[concat(parameters('prj'),'-',parameters('env'),'-',parameters('servername'),'-nic')]"
  },
  "resources": [
    {
      "type": "Microsoft.Network/virtualNetworks",
      "apiVersion": "2022-05-01",
      "name": "[variables('virtualNetworks_name')]",
      "location": "japaneast",
      "dependsOn": [
        "[resourceId('Microsoft.Network/networkSecurityGroups', variables('networkSecurityGroups_name'))]"
      ],
      "properties": {
        "addressSpace": {
          "addressPrefixes": [
            "172.16.0.0/20"
          ]
        },
        "dhcpOptions": {
          "dnsServers": []
        },
        "subnets": [
          {
            "name": "main-subnet",
            "id": "[resourceId('Microsoft.Network/virtualNetworks/subnets', variables('virtualNetworks_name'), 'main-subnet')]",
            "properties": {
              "addressPrefix": "172.16.0.0/24",
              "networkSecurityGroup": {
                "id": "[resourceId('Microsoft.Network/networkSecurityGroups', variables('networkSecurityGroups_name'))]"
              },
              "serviceEndpoints": [],
              "delegations": [],
              "privateEndpointNetworkPolicies": "Enabled",
              "privateLinkServiceNetworkPolicies": "Enabled"
            },
            "type": "Microsoft.Network/virtualNetworks/subnets"
          }
        ],
        "virtualNetworkPeerings": [],
        "enableDdosProtection": false
      }
    },
    {
      "type": "Microsoft.Network/networkSecurityGroups",
      "apiVersion": "2022-05-01",
      "name": "[variables('networkSecurityGroups_name')]",
      "location": "japaneast",
      "properties": {
        "securityRules": []
      }
    },
    {
      "type": "Microsoft.Compute/virtualMachines",
      "apiVersion": "2022-08-01",
      "name": "[variables('virtualMachines_name')]",
      "location": "japaneast",
      "dependsOn": [
        "[resourceId('Microsoft.Network/networkInterfaces', variables('networkInterfaces_name'))]"
      ],
      "properties": {
        "hardwareProfile": {
          "vmSize": "Standard_B2s"
        },
        "storageProfile": {
          "imageReference": {
            "publisher": "MicrosoftWindowsServer",
            "offer": "WindowsServer",
            "sku": "2019-Datacenter",
            "version": "latest"
          },
          "osDisk": {
            "osType": "Windows",
            "name": "[variables('virtualMachines_osdisk')]",
            "createOption": "FromImage",
            "caching": "ReadWrite",
            "writeAcceleratorEnabled": false,
            "managedDisk": {
              "storageAccountType": "Standard_LRS"
            },
            "deleteOption": "Detach",
            "diskSizeGB": 127
          },
          "dataDisks": []
        },
        "osProfile": {
          "computerName": "winsvr",
          "adminUsername": "[variables('virtualMachines_username')]",
          "adminPassword": "[variables('virtualMachines_password')]",
          "windowsConfiguration": {
            "provisionVMAgent": true,
            "enableAutomaticUpdates": true,
            "patchSettings": {
              "patchMode": "AutomaticByOS",
              "assessmentMode": "ImageDefault",
              "enableHotpatching": false
            },
            "winRM": {
              "listeners": []
            },
            "enableVMAgentPlatformUpdates": false
          },
          "secrets": [],
          "allowExtensionOperations": true
        },
        "networkProfile": {
          "networkInterfaces": [
            {
              "id": "[resourceId('Microsoft.Network/networkInterfaces', variables('networkInterfaces_name'))]",
              "properties": {
                "primary": true
              }
            }
          ]
        },
        "diagnosticsProfile": {
          "bootDiagnostics": {
            "enabled": false
          }
        },
        "priority": "Regular",
        "extensionsTimeBudget": "PT1H30M"
      }
    },
    {
      "type": "microsoft.devtestlab/schedules",
      "apiVersion": "2018-09-15",
      "name": "[concat('shutdown-computevm-', variables('virtualMachines_name'))]",
      "location": "japaneast",
      "dependsOn": [
        "[resourceId('Microsoft.Compute/virtualMachines', variables('virtualMachines_name'))]"
      ],
      "properties": {
        "status": "Enabled",
        "taskType": "ComputeVmShutdownTask",
        "dailyRecurrence": {
          "time": "0400"
        },
        "timeZoneId": "Tokyo Standard Time",
        "notificationSettings": {
          "status": "Disabled",
          "timeInMinutes": 30
        },
        "targetResourceId": "[resourceId('Microsoft.Compute/virtualMachines', variables('virtualMachines_name'))]"
      }
    },
    {
      "type": "Microsoft.Network/networkInterfaces",
      "apiVersion": "2022-05-01",
      "name": "[variables('networkInterfaces_name')]",
      "location": "japaneast",
      "dependsOn": [
        "[resourceId('Microsoft.Network/virtualNetworks', variables('virtualNetworks_name'))]",
        "[resourceId('Microsoft.Network/publicIPAddresses', variables('publicIPAddresses_name'))]"
      ],
      "kind": "Regular",
      "properties": {
        "ipConfigurations": [
          {
            "name": "internal",
            "id": "[concat(resourceId('Microsoft.Network/networkInterfaces', variables('networkInterfaces_name')), '/ipConfigurations/internal')]",
            "etag": "W/\"2391a46d-ac69-4b9c-b2f0-f85ef5952994\"",
            "type": "Microsoft.Network/networkInterfaces/ipConfigurations",
            "properties": {
              "provisioningState": "Succeeded",
              "privateIPAddress": "172.16.0.4",
              "privateIPAllocationMethod": "Dynamic",
              "publicIPAddress": {
                "id": "[resourceId('Microsoft.Network/publicIPAddresses', variables('publicIPAddresses_name'))]"
              },
              "subnet": {
                "id": "[resourceId('Microsoft.Network/virtualNetworks/subnets', variables('virtualNetworks_name'), 'main-subnet')]"
              },
              "primary": true,
              "privateIPAddressVersion": "IPv4"
            }
          }
        ],
        "dnsSettings": {
          "dnsServers": []
        },
        "enableAcceleratedNetworking": false,
        "enableIPForwarding": false,
        "disableTcpStateTracking": false,
        "nicType": "Standard"
      }
    },
    {
      "type": "Microsoft.Network/publicIPAddresses",
      "apiVersion": "2022-05-01",
      "name": "[variables('publicIPAddresses_name')]",
      "location": "japaneast",
      "sku": {
        "name": "Basic",
        "tier": "Regional"
      },
      "properties": {
        "ipAddress": "20.63.159.5",
        "publicIPAddressVersion": "IPv4",
        "publicIPAllocationMethod": "Dynamic",
        "idleTimeoutInMinutes": 4,
        "ipTags": []
      }
    }
  ]
}
